include_directories(${OpenSim_SOURCE_DIR}
                    ${OpenSim_SOURCE_DIR}/Vendors)
					
if(BUILD_TESTING)
    add_subdirectory(PredSim)
    add_subdirectory(PredSim_pp)
    add_subdirectory(PredSim_SSCM)
    add_subdirectory(PredSim_SSCM_pp)
    add_subdirectory(TrackSim_1)
    add_subdirectory(TrackSim_2)
    add_subdirectory(PredSimProsthesis)
    add_subdirectory(PredSimProsthesis_pp)
    add_subdirectory(PredSim_2D)
    add_subdirectory(PredSim_2D_pp)
    add_subdirectory(Pendulum_2dofs)
    add_subdirectory(Pendulum_2dofs_osim)
    add_subdirectory(Pendulum_3dofs)
    add_subdirectory(Pendulum_4dofs)
    add_subdirectory(Pendulum_5dofs)
    add_subdirectory(Pendulum_6dofs)
    add_subdirectory(Pendulum_7dofs)
    add_subdirectory(Pendulum_8dofs)
    add_subdirectory(Pendulum_9dofs)
    add_subdirectory(Pendulum_10dofs)
    add_subdirectory(PredSim_CP)
    add_subdirectory(PredSim_mtp)
    add_subdirectory(PredSim_mtp_pp)
    add_subdirectory(TrackSim_mtp_1)
    add_subdirectory(TrackSim_mtp_2)
    add_subdirectory(TrackSim_mtp_2_5cs)
    add_subdirectory(TrackSim_mtp_2_4cs)
    add_subdirectory(TrackSim_mtp_2_4csb)
    add_subdirectory(TrackSim_mtp_2_5csb)   
    add_subdirectory(PredSim_mtp_cm1)
    add_subdirectory(PredSim_mtp_pp_cm1)    
    add_subdirectory(TrackSim_mtpPin_1)
    add_subdirectory(TrackSim_mtpPin_2_5csb)
    add_subdirectory(PredSim_mtpPin_cm2)
    add_subdirectory(PredSim_mtpPin_pp_cm2)       
    add_subdirectory(TrackSim_mtpPin_2_4cs)
    add_subdirectory(TrackSim_mtpPin_2_6cs)
    add_subdirectory(PredSim_mtpPin_cm3)
    add_subdirectory(PredSim_mtpPin_pp_cm3) 
    add_subdirectory(DummyModel)    
    add_subdirectory(PredSim_v2) 
    add_subdirectory(PredSim_v2_pp)
	add_subdirectory(TrackSim_1_kneeCont)
	add_subdirectory(TrackSim_1_kneeCont_debug)
	add_subdirectory(TrackSim_2_kneeCont)
	add_subdirectory(TrackSim_2_kneeContNegSl)
	add_subdirectory(TrackSim_2_kneeCont_forDebug)
	add_subdirectory(TrackSim_2_kneeCont_withTanForce)
	add_subdirectory(oneLeg)
	add_subdirectory(oneHumanArm)
	add_subdirectory(trebuchet)
	add_subdirectory(robotarm4dof_EMARO)
	add_subdirectory(cartpole_invpendulum2dof)
	add_subdirectory(RightRatHindlimb)
	add_subdirectory(RightRatHindlimb_Zhong)
	add_subdirectory(robotarm3dof_2_1)
	add_subdirectory(robotarm4dof_2_1_1_shovel)
	add_subdirectory(robotdog)
	add_subdirectory(robotdog_11dof)
	add_subdirectory(gait10dof)
	add_subdirectory(Pendulum_4dofs_human)
	add_subdirectory(crane_ball)
	add_subdirectory(Sphere_mesh)
	add_subdirectory(KneeProsthesis)
	add_subdirectory(KneeProsthesis_forDebug)
	add_subdirectory(testExpressionGraph)
	add_subdirectory(StewartPlatform)
	add_subdirectory(oneLeg_withContact)
	add_subdirectory(RightRatHindlimb_Zhong_InertiaVar)
	add_subdirectory(PredSim_v2_kneeCont)
	add_subdirectory(PredSim_v2_kneeCont_forDebug)
	add_subdirectory(TrackSim_2_kneeCont_KCFasinput)
	add_subdirectory(PredSim_v2_kneeCont_KCFasinput)
	add_subdirectory(PredSim_v2_kneeCont_KCFasinput_forDebug)
	add_subdirectory(gait2legs1arm_21dof)
	add_subdirectory(robotarm5dof_3_1_1)
	add_subdirectory(robotarm7dof_3_3_1)
	add_subdirectory(Rugby_generic_1)
endif()



